apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-pod
  name: 6309658406-2
spec:
  containers:
    - name: iris-web
      image: kran13200/iris_web:latest
      ports:
        - name: http
          containerPort: 5000
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-pod
  name: 6309658406-1

spec:
  containers:
    - name: iris-web
      image: kran13200/iris_web:latest
      ports:
        - name: http
          containerPort: 5000
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-pod
  ports:
  - port: 5001
    targetPort: 5000
